---
title: "Reward Matrix"
author: "Min-Chun Shih"
output: 
  html_document:
    toc: true
    toc_float: TRUE
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(gridExtra)
```

Only use data from season 2013-2014

```{r, eval = FALSE}
# import data
# # ======= game type (regular season/playoffs) =======
game <- read.csv("../data/game.csv", sep = ";")
game$Season <- as.character(game$Season)
game <- game[which(game$Season == "2013-2014"), ]

# ======= goals records =======
state <- read.csv("../data/event_goal.csv", header = FALSE)
names(state) <- c(
  "GoalId",
  "GameId",
  "AwayTeamId",
  "HomeTeamId",
  "EventNumber",
  "PeriodNumber",
  "EventTime",
  "ScoringTeam",
  "ScoringTeamId",
  "Disposition",
  "GoalScorerNumber",
  "GoalScorerId",
  "NumGoals",
  "FirstAssistNumber",
  "FirstAssistId",
  "NumAssistsFirstPlayer",
  "SecondAssistNumber",
  "SecondAssistId",
  "NumAssistsSecondPlayer",
  "ShotType",
  "Zone",
  "ShotDistance")

# select the columns
state <- state[, c("GameId", "AwayTeamId", "HomeTeamId", "PeriodNumber", "EventTime", "ScoringTeamId")]

# merge state data and game data to get Season and SeasonType
state <- left_join(game, state)
state <- state[which(state$PeriodNumber %in% 1:3), ]

# ======= Manpower =======
events <- read.csv("../data/play_by_play_events.csv", sep = ";")

# merge with game data to get Season and SeasonType
events <- left_join(game, events)
events <- events[which(events$PeriodNumber %in% 1:3), ]

# compute manpower for away and home teams
for (i in 12:29) {
  events[, i] <- as.character(events[, i])
}
manpowewr <- unlist(lapply(1:nrow(events), function(x) {
  length(which(events[x, 12:20] != "NULL"))
}))
events$ManpowerAway <- manpowewr

manpowewr <- unlist(lapply(1:nrow(events), function(x) {
  length(which(events[x, 21:29] != "NULL"))
}))
events$ManpowerHome <- manpowewr

manpower <- events[, c("GameId", "PeriodNumber", "EventTime", "ManpowerAway", "ManpowerHome")]
manpower <- unique(manpower)
save(manpower, file = "../data/manpower.Rdata")

# filter GOAL events
events <- events[which(events$EventType =="GOAL"), ]
events <- events[, c("GameId", "PeriodNumber", "EventTime", "ManpowerAway", "ManpowerHome")]



state$EventTime <- as.character(state$EventTime)
events$EventTime <- as.character(events$EventTime)

df <- inner_join(state, events)

df$EventTime <- as.character(df$EventTime)
df$seconds <- as.integer(substr(df$EventTime, 4, 5))*60 + 
  as.integer(substr(df$EventTime, 7, 8))


save(df, file = "../data/seaon20132014.rdata")
```



```{r}
load("../data/seaon20132014.rdata")
```


# Number of games
```{r}
kable(table((df[, c("GameId", "SeasonType")])$SeasonType), caption = "The amount of Games") %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```

# Distribution of goals in different period time
```{r}
i <- which(df$PeriodNumber == 1)
ii <- intersect(which(df$SeasonType == "Regular Season"), i)
plot1 <- ggplot(df[ii, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Regular Season)",
       subtitle="PeriodNumber is 1") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[ii, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
jj <- intersect(which(df$SeasonType == "Playoffs"), i)
plot2 <- ggplot(df[jj, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Playoffs)",
       subtitle="PeriodNumber is 1") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[jj, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
grid.arrange(plot1, plot2)

i <- which(df$PeriodNumber %in% c(2) == TRUE)
ii <- intersect(which(df$SeasonType == "Regular Season"), i)
plot1 <- ggplot(df[ii, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Regular Season)",
       subtitle="PeriodNumber is 2") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[ii, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
jj <- intersect(which(df$SeasonType == "Playoffs"), i)
plot2 <- ggplot(df[jj, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Playoffs)",
       subtitle="PeriodNumber is 2") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[jj, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
grid.arrange(plot1, plot2)

i <- which(df$PeriodNumber %in% c(3) == TRUE)
ii <- intersect(which(df$SeasonType == "Regular Season"), i)
plot1 <- ggplot(df[ii, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Regular Season)",
       subtitle="PeriodNumber is 3") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[ii, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
jj <- intersect(which(df$SeasonType == "Playoffs"), i)
plot2 <- ggplot(df[jj, ], aes(x = seconds)) + 
  geom_histogram(color="black", fill="gold1", alpha=0.7) +
  theme_bw() +
  labs(title = "The distibution of Goals in Times (Playoffs)",
       subtitle="PeriodNumber is 3") +
  geom_hline(aes(yintercept=
                   mean(table(cut(df[jj, "seconds"],
                                  breaks = 30)))),
             color="red", linetype="dashed", size=0.5)
grid.arrange(plot1, plot2)



library(data.table)
df <- data.table(df)
```
```{r}
rm(plot1, plot2, i, ii, jj)
```

```{r, eval = FALSE}
library(tidyr)

# ======= game type (regular season/playoffs) =======
game <- read.csv("../data/game.csv", sep = ";")
game$Season <- as.character(game$Season)
game <- game[which(game$Season == "2013-2014"), ]

# ======= goals records =======
state <- read.csv("../data/event_goal.csv", header = FALSE)
names(state) <- c(
  "GoalId",
  "GameId",
  "AwayTeamId",
  "HomeTeamId",
  "EventNumber",
  "PeriodNumber",
  "EventTime",
  "ScoringTeam",
  "ScoringTeamId",
  "Disposition",
  "GoalScorerNumber",
  "GoalScorerId",
  "NumGoals",
  "FirstAssistNumber",
  "FirstAssistId",
  "NumAssistsFirstPlayer",
  "SecondAssistNumber",
  "SecondAssistId",
  "NumAssistsSecondPlayer",
  "ShotType",
  "Zone",
  "ShotDistance")

# select the columns
state <- state[, c("GameId", "AwayTeamId", "HomeTeamId", "PeriodNumber", "EventTime", "ScoringTeamId")]

# merge state data and game data to get Season and SeasonType
state <- left_join(game, state)


winer <- state %>% 
  group_by(GameId, ScoringTeamId) %>%
  summarise(goals = n())

# compute the goals of AwayTeam and HomeTeam for each game
goals_end <- distinct(state %>%
  select(GameId, AwayTeamId, HomeTeamId))

goals_end$AwayGoals <- 0
goals_end$HomeGoals <- 0

for (i in 1:nrow(goals_end)) {
  id <- goals_end$GameId[i]
  j <- which(winer$GameId == id)
  for (jj in j) {
    if(winer[jj, ]$ScoringTeamId == goals_end$AwayTeamId[i]) {
      goals_end$AwayGoals[i] <- winer[jj, ]$goals
    } else {
      goals_end$HomeGoals[i] <- winer[jj, ]$goals
    }
  }
}


winer <- winer %>%
  group_by(GameId) %>%
  filter(goals == max(goals)) %>%
  select(GameId, ScoringTeamId)
names(winer)[2] <- "Winer"

goals_end <- full_join(goals_end, winer)
save(goals_end, file = "../data/goals_end.Rdata")
```

```{r, eval = FALSE}
load("../data/goals_end.Rdata")
```

```{r, eval = FALSE}
### Compute seconds ###
# compute seconds 將時間換算成秒
df$seconds <- (df$PeriodNumber - 1)*20*60 + df$seconds
# order by seconds 根據節數與時間秒數排序
df <- df[order(df$GameId, df$seconds), ]

### compute GA&GF for period 1-3 ###
# get away team goals
df$AwayTeamGoals <- ifelse(df$ScoringTeamId == df$AwayTeamId, 1, 0)
# get home team goals
df$HomeTeamGoals <- ifelse(df$ScoringTeamId == df$HomeTeamId, 1, 0)
# compute cumulate goals
df <- data.table(df)
GF <- df[, list(GF = cumsum(AwayTeamGoals)), by=list(GameId)]
GA <- df[, list(GA = cumsum(HomeTeamGoals)), by=list(GameId)]
df <- cbind(df, GF[, -1])
df <- cbind(df, GA[, -1])
# df <- data.frame(df)
df <- df[, c(-12, -13)]

df <- left_join(df, goals_end)

result_after_3_period <- df %>% 
  group_by(GameId) %>%
  filter(seconds == max(seconds)) %>%
  select(GameId, GF, GA)

result_after_3_period$result <- ifelse(result_after_3_period$GF == result_after_3_period$GA,
                                       "tied", "")
result_after_3_period <- result_after_3_period %>% select(GameId, result)

df$HomeResult <- ifelse(df$HomeTeamId == df$Winer, "win", "lose")

df <- left_join(df, result_after_3_period)
df$HomeResult <- ifelse(df$result == "", df$HomeResult, paste0(df$result, "_", df$HomeResult))
df$result <- NULL

save(df, file = "../data/df.Rdata")
```

```{r}
load(file = "../data/df.Rdata")
```


```{r}
# manpower for every events, if will be used for compute time interval's manpower
load("../data/manpower.Rdata")
manpower <- manpower[-which(manpower$ManpowerAway == 0 | manpower$ManpowerHome == 0), ]
manpower$seconds <- as.integer(substr(manpower$EventTime, 4, 5))*60 + 
  as.integer(substr(manpower$EventTime, 7, 8))
manpower$seconds <- (manpower$PeriodNumber - 1)*20*60 + manpower$seconds
manpower <- manpower[, c("GameId", "ManpowerAway", "ManpowerHome", "seconds")]
```

```{r}
# get the conut matrix
get_count_matrix <- function(df, time_interval, type = c("ratio", "count_before")) {
  # compute interval
  interval <- cut(df$seconds, seq(0, 20*60*3, time_interval))
  
  df$interval <- interval
  df$index <- as.integer(df$interval)
  if (type == "ratio") {
    df$ratio <- (time_interval*df$index - df$seconds)/time_interval
  }
  if (type == "count_before") {
    df$ratio <- 1
  }
  
  count <- data.table(GameId = as.character(), interval = as.character(),
                   GF = as.integer(), GA = as.integer(), count = as.numeric(), 
                   ManpowerAway = as.integer(), ManpowerHome = as.integer(),
                   AwayGoals = as.integer(), HomeGoals = as.integer(), HomeResult = as.character())
  
  interval_levels <- factor(levels(interval), levels = levels(interval))
  n_interval <- length(levels(interval))
  
  d <- df %>%
    select(GameId, interval, GF, GA, count = ratio, 
           ManpowerAway, ManpowerHome, AwayGoals, HomeGoals, HomeResult)
  
  ids <- unique(d$GameId)
  
  for (id in ids) {
    # print (id)
    
    game_manpower <- manpower[which(manpower$GameId == id), ]
    
    t <- d[which(d$GameId == id), ] # the same game in d
    n <- nrow(t)
    first <- as.integer(t$interval)[1]
    freq <- data.frame(table(t$interval))
    AwayGoals <- t$AwayGoals[1]
    HomeGoals <- t$HomeGoals[1]
    HomeResult <- t$HomeResult[1]
  
    # the 
    freq_0_interval <- which(freq$Freq == 0)
    for (i in freq_0_interval) {
      manpower_row <- which((game_manpower$seconds > 
                                 as.integer(interval_levels[i])*time_interval)  == TRUE)[1]
      manpower_away <- game_manpower[manpower_row, "ManpowerAway"]
      manpower_home <- game_manpower[manpower_row, "ManpowerHome"]

      
      if (i < first) {
        l = list(t, data.table(GameId = id, interval = interval_levels[i],
                               GF = 0, GA = 0, count = 1.0, 
                               ManpowerAway = manpower_away, 
                               ManpowerHome = manpower_home,
                               AwayGoals = AwayGoals, HomeGoals = HomeGoals, 
                               HomeResult = HomeResult))
      } else {
        ii <- which(t$interval == interval_levels[i-1])
        ii <- ii[length(ii)]
        l <- list(t, data.table(GameId = id, interval = interval_levels[i],
                                GF = t[ii, ]$GF, GA = t[ii, ]$GA, count = 1.0, 
                                ManpowerAway = manpower_away, 
                                ManpowerHome = manpower_home,
                                AwayGoals = AwayGoals, HomeGoals = HomeGoals,
                                HomeResult = HomeResult))
      }
      t <- rbindlist(l)
    }
  
    last_interval_level <- ""
    for (i in 1:n) {
      manpower_row <- which((game_manpower$seconds > 
                                 as.integer(interval_levels[i])*time_interval)  == TRUE)[1]
      manpower_away <- game_manpower[manpower_row, "ManpowerAway"]
      manpower_home <- game_manpower[manpower_row, "ManpowerHome"]
      ii <- as.integer(t[i, ]$interval)
  
      
      if (last_interval_level != interval_levels[ii]) {
        if (i == 1) {
          l <- list(t, data.table(GameId = id, interval = interval_levels[ii],
                                  GF = 0, GA = 0, count = 1 - t[1, ]$count, 
                                  ManpowerAway = manpower_away, 
                                  ManpowerHome = manpower_home,
                                  AwayGoals = AwayGoals, HomeGoals = HomeGoals,
                                  HomeResult = HomeResult))
        } else {
          l <- list(t, data.table(GameId = id, interval = interval_levels[ii],
                                  GF = t[i-1, ]$GF, GA = t[i-1, ]$GA,
                                  count = 1 - t[i, ]$count, 
                                  ManpowerAway = 0, ManpowerHome = 0,
                                  AwayGoals = AwayGoals, HomeGoals = HomeGoals,
                                  HomeResult = HomeResult))
        }
      } else {
        next
      }
      t <- rbindlist(l)
      last_interval_level <- interval_levels[ii]
    }
  
    t <- t[order(t$interval, t$GF, t$GA), ]
  
    l <- list(count, t)
    count <- rbindlist(l)
  }
  
  # group by (interval, GF, GA, ManpowerAway, ManpowerHome, AwayGoals, HomeGoals)
  count_matrix <- count %>%
    group_by(interval, GF, GA,
             ManpowerAway, ManpowerHome, AwayGoals, HomeGoals, HomeResult) %>%
    summarise(count = sum(count))
  
  count_matrix$ManpowerDiff <- count_matrix$ManpowerHome - count_matrix$ManpowerAway
  count_matrix$GoalDiff <- count_matrix$HomeGoals - count_matrix$AwayGoals
  
  return(count_matrix)
}
```



***

# Count Matrix
```{r}
# function
goal_ditribution_plot <- function(df, time_interval) {
  d <- data.frame(table(cut(df$seconds, seq(0, 20*60*3, time_interval))))
  d$seq <- 1:nrow(d)
  d$Var1 <- as.character(d$Var1)
  barplot(d$Freq, main = paste("The goal distribution of time interval =", time_interval, "seconds"))
}

count_group_homeresult <- function(count_matrix, time_interval) {
  count <- count_matrix %>%
    group_by(interval, HomeResult) %>%
    summarise(count = sum(count))

  # lose
  count_lose <- count[which(count$HomeResult == "lose"), ]
  plot(count_lose$interval, count_lose$count, xaxt="n", 
       main = "lose")
  lines(count_lose$interval, count_lose$count)
  abline(h = mean(count_lose$count), col = "red", lty=2)
  labs <- levels(count_lose$interval)
  text(x=as.integer(count_lose$interval) - 1, 
       y=min(count_lose$count) - (max(count_lose$count)- min(count_lose$count))/10, 
       labs, xpd=TRUE, srt=45, cex=0.5)

  # win
  count_win <- count[which(count$HomeResult == "win"), ]
  plot(count_win$interval, count_win$count, main = "win", xaxt="n")
  lines(count_win$interval, count_win$count)
  abline(h = mean(count_win$count), col = "red", lty=2)
  labs <- levels(count_win$interval)
  text(x=as.integer(count_win$interval) - 1, 
       y=min(count_win$count) - (max(count_win$count)- min(count_win$count))/10, 
       labs, xpd=TRUE, srt=45, cex=0.5)

  # tied win
  count_tied_lose <- count[which(count$HomeResult == "tied_lose"), ]
  plot(count_tied_lose$interval, count_tied_lose$count, main = "tied lose", xaxt="n")
  lines(count_tied_lose$interval, count_tied_lose$count)
  abline(h = mean(count_tied_lose$count), col = "red", lty=2)
  labs <- levels(count_tied_lose$interval)
  text(x=as.integer(count_tied_lose$interval) - 1, 
       y=min(count_tied_lose$count) - (max(count_tied_lose$count)- min(count_tied_lose$count))/10, 
       labs, xpd=TRUE, srt=45, cex=0.5)

  # tied win
  count_tied_win <- count[which(count$HomeResult == "tied_win"), ]
  plot(count_tied_win$interval, count_tied_win$count, main = "tied win", xaxt="n")
  lines(count_tied_win$interval, count_tied_win$count)
  abline(h = mean(count_tied_win$count), col = "red", lty=2)
  labs <- levels(count_tied_win$interval)
  text(x=as.integer(count_tied_win$interval) - 1, 
       y=min(count_tied_win$count) - (max(count_tied_win$count)- min(count_tied_win$count))/10, 
       labs, xpd=TRUE, srt=45, cex=0.5)


  count_interval <- data.frame(Type = as.character(), Mean = as.numeric(), Range = as.numeric(),
                        Max = as.numeric(), Min = as.numeric())
  count_interval <- rbind(count_interval, data.frame(Type = "Lose", Mean = mean(count_lose$count), 
                                         Range = max(count_lose$count) - min(count_lose$count),
                                         Max = max(count_lose$count), Min = min(count_lose$count)))
  count_interval <- rbind(count_interval, data.frame(Type = "Win", Mean = mean(count_win$count), 
                                         Range = max(count_win$count) - min(count_win$count),
                                         Max = max(count_win$count), Min = min(count_win$count)))
  count_interval <- rbind(count_interval, data.frame(Type = "Tied Lose", Mean = mean(count_tied_lose$count), 
                                         Range = max(count_tied_lose$count) - min(count_tied_lose$count),
                                         Max = max(count_tied_lose$count), Min = min(count_tied_lose$count)))
  count_interval <- rbind(count_interval, data.frame(Type = "Tied Win", Mean = mean(count_tied_win$count), 
                                         Range = max(count_tied_win$count) - min(count_tied_win$count),
                                         Max = max(count_tied_win$count), Min = min(count_tied_win$count)))

  return(list(count_interval = count_interval, count = count, 
              count_lose = count_lose, count_win = count_win, 
              count_tied_lose = count_tied_lose, count_tied_win = count_tied_win))
}
```


## Group by Home Team Result(win/lose/tied win/tied lose)
### Time interval = 120 seconds
```{r}
time_interval <- 120

goal_ditribution_plot(df, time_interval)

# count_matrix_120 <- get_count_matrix(df, time_interval, type = "ratio")
# save(count_matrix_120, file = "../data/count_matrix_120.Rdata")
load("../data/count_matrix_120.Rdata")

count_120 <- count_group_homeresult(count_matrix_120, time_interval)

kable(count_120$count_interval, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```


### Time interval = 60 seconds
```{r}
time_interval <- 60

goal_ditribution_plot(df, time_interval)

# count_matrix_60 <- get_count_matrix(df, time_interval, type = "ratio")
# save(count_matrix_60, file = "../data/count_matrix_60.Rdata")
load("../data/count_matrix_60.Rdata")

count_60 <- count_group_homeresult(count_matrix_60, time_interval)

kable(count_60$count_interval, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```


### Time interval = 30 seconds
```{r}
time_interval <- 30

goal_ditribution_plot(df, time_interval)

# count_matrix_30 <- get_count_matrix(df, time_interval, type = "ratio")
# save(count_matrix_30, file = "../data/count_matrix_30.Rdata")
load("../data/count_matrix_30.Rdata")

count_30 <- count_group_homeresult(count_matrix_30, time_interval)
kable(count_30$count_interval, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```

```{r}
cc <- count_30$count_interval
cc$Interval <- 30
statistics <- cc

cc <- count_60$count_interval
cc$Interval <- 60
statistics <- rbind(statistics, cc)

cc <- count_120$count_interval
cc$Interval <- 120
statistics <- rbind(statistics, cc)

rm(cc)
statistics <- statistics[order(statistics$Type), ]
kable(statistics, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```


## Group by GoalDiff & Result
```{r}
count_matrix_diff_30  <- count_matrix_30 %>%
  group_by(interval, HomeResult, GoalDiff) %>%
  summarise(count = sum(count))

table(count_matrix_diff_30$HomeResult, count_matrix_diff_30$GoalDiff)

cc <- count_matrix_diff_30 %>%
  group_by(HomeResult, GoalDiff) %>%
  summarise(mean = mean(count), max = max(count), min = min(count))
  
kable(cc, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")



# lose
count_lose <- count_matrix_diff_30[which(count_matrix_diff_30$HomeResult == "lose" & 
                                           count_matrix_diff_30$GoalDiff == -1), ]
plot(count_lose$interval, count_lose$count, xaxt="n", 
     main = "lose, GoalDiff = -1")
lines(count_lose$interval, count_lose$count)
abline(h = mean(count_lose$count), col = "red", lty=2)
labs <- levels(count_lose$interval)
text(x=as.integer(count_lose$interval) - 1, 
     y=min(count_lose$count) - (max(count_lose$count)- min(count_lose$count))/10, 
     labs, xpd=TRUE, srt=45, cex=0.5)


 # win
count_win <- count_matrix_diff_30[which(count_matrix_diff_30$HomeResult == "win" & 
                                           count_matrix_diff_30$GoalDiff == 1), ]
plot(count_win$interval, count_win$count, xaxt="n", 
     main = "win, GoalDiff = 1")
lines(count_win$interval, count_win$count)
abline(h = mean(count_win$count), col = "red", lty=2)
labs <- levels(count_win$interval)
text(x=as.integer(count_win$interval) - 1, 
     y=min(count_win$count) - (max(count_win$count)- min(count_win$count))/10, 
     labs, xpd=TRUE, srt=45, cex=0.5)



```


## Different counting method

```{r}
time_interval <- 30

# count_matrix_30_before <- get_count_matrix(df, time_interval, type = "count_before")
# save(count_matrix_30_before, file = "../data/count_matrix_30_before.Rdata")
load("../data/count_matrix_30_before.Rdata")

count_30_bofore <- count_group_homeresult(count_matrix_30_before, time_interval)
kable(count_30_bofore$count_interval, caption = paste("Statistics for count interval = ", time_interval)) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, 
                position = "left")
```


